version: '3.8'

services:
  apache:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - XDEBUG_CONFIG="discover_client_host=true"
    volumes:
      - ..:/var/www/html
    ports:
      - 127.0.0.1:80:80
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: mydb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysecret
    ports:
      - 127.0.0.1:3306:3306
      